import os
import scripts.app_helper as app

def initArgument(name, defVal):
    val = ARGUMENTS.get(name, '')
    if len(val) == 0:
        ARGUMENTS[name] = defVal

ARGUMENTS['LCD'] = '800_480'
helper = app.Helper(ARGUMENTS);
helper.set_dll_def('src/dirty_rect_view.def').set_libs(['dirty_rect_view']).call(DefaultEnvironment)

SConscriptFiles = ['src/SConscript', 'demos/SConscript', 'tests/SConscript']
SConscript(SConscriptFiles)
